version: "3"
services:
    php-actions:
        image: sptr/php-dev74-mysql:latest
        container_name: ${COMPOSE_PROJECT_NAME}-php
        hostname: ${COMPOSE_PROJECT_NAME}-php
        restart: always
        environment:
            XDEBUG_CONFIG: "remote_host=${XDEBUG_REMOTE_HOST} remote_port=${XDEBUG_REMOTE_PORT} remote_enable=1"
        links:
            - nginx-actions:${NGINX_HOSTNAME}
        volumes:
            - ./:/var/www/src
        working_dir: /var/www/src
        networks:
            - all
            - default
    nginx-actions:
        image: nginx:1.15-alpine
        labels:
            - "traefik.frontend.rule=Host:${NGINX_HOSTNAME}"
            - "traefik.docker.network=sptr_all"
        container_name: ${COMPOSE_PROJECT_NAME}-nginx
        restart: on-failure
        volumes:
            - ./resources/docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/src
        networks:
            - all
            - default
networks:
    all:
        external:
            name: sptr_all
