# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: [pull_request]
#
#    # Allows you to run this workflow manually from the Actions tab
#    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    test:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: false
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: cakephp
                ports:
                    - 3306/tcp
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        steps:
            - uses: actions/checkout@v2

#            - name: Shutdown Ubuntu MySQL (SUDO)
#              run: sudo service mysql stop

#            - name: Test mysql
#              run: mysql -h127.0.0.1 -P${{ job.services.mysql.ports['3306'] }} -uroot -proot -e 'SHOW DATABASES'

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  extensions: bcmath, iconv, ctype, gd, mbstring, mysqli, pdo, pdo_mysql, sockets, zip, soap, intl

#            - name: Setup config
#              run: |
#                echo "<?php
#                return ['Datasources' => ['test' => ['username' => 'root', 'password' => 'root', 'host' => '127.0.0.1', 'port' => '${{ job.services.mysql.ports['3306'] }}', 'database' => 'test_myapp', 'persistent' => false, 'encoding' => 'utf8'], 'default' => ['username' => 'root', 'password' => 'root', 'host' => '127.0.0.1', 'port' => '${{ job.services.mysql.ports['3306'] }}', 'database' => 'test_myapp', 'persistent' => false, 'encoding' => 'utf8']]];" > ./config/app_local.php

            - name: Install dependencies
              run: |
                composer install --no-progress --prefer-dist --optimize-autoloader
                composer run-script post-install-cmd --no-interaction

            - name: PHPUnit
              run: composer test
              env:
                DATABASE_URL: "mysql://root:root@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/cakephp?init[]=SET sql_mode = \"STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION\""

    static-analysis:
      name: Coding Standard
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.4'
            extensions: mbstring, intl

        - name: Install dependencies
          run: composer install --no-progress --prefer-dist --optimize-autoloader

        - name: Psalm
          run: ./vendor/bin/psalm.phar

    coding-standard:
      name: Coding Standard
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.4'
            extensions: mbstring, intl

        - name: Install dependencies
          run: composer install --no-progress --prefer-dist --optimize-autoloader

        - name: PHP CodeSniffer
          run: composer cs-check
